const { writeFile } = require("./gen-helper.cjs");

const REASONING = [
  /* IQ - number series */
  ["iq", "Number Series", "easy", "Find the next number: 2, 6, 12, 20, 30, ?", ["36", "40", "42", "44"], "C", "The differences are 4, 6, 8, 10, so the next difference is 12: 30 + 12 = 42.", ["series", "iq"]],
  ["iq", "Number Series", "easy", "Find the next number: 3, 9, 27, 81, ?", ["162", "243", "324", "108"], "B", "Each term is multiplied by 3: 81 x 3 = 243.", ["series", "iq"]],
  ["iq", "Letter & Symbol Series", "medium", "Find the next letter: A, C, F, J, O, ?", ["S", "T", "U", "V"], "C", "The gaps increase by 1: +2, +3, +4, +5, so next is +6: O + 6 = U.", ["series", "letters"]],
  ["iq", "Letter & Symbol Series", "medium", "What comes next in the series: 1A, 3C, 6F, 10J, ?", ["13M", "15O", "14M", "16P"], "B", "Numbers add 2,3,4,5 (next 15); letters advance by 2,3,4,5 positions from A (next O).", ["series"]],
  ["iq", "Classification", "easy", "Which one does not belong to the group?", ["Tiger", "Lion", "Cat", "Wolf"], "D", "Tiger, lion and cat belong to the cat family (Felidae); wolf belongs to the dog family.", ["classification"]],
  ["iq", "Odd One Out", "medium", "Find the odd one out:", ["11", "17", "23", "27"], "D", "11, 17 and 23 are prime numbers; 27 is composite (3 cubed).", ["classification", "numbers"]],
  ["iq", "Word Analogies", "easy", "Book is to Reading as Fork is to:", ["Cooking", "Eating", "Spoon", "Kitchen"], "B", "A book is used for reading; a fork is used for eating.", ["analogy"]],
  ["iq", "Number Analogies", "medium", "If 2 : 8 :: 5 : ?", ["20", "25", "30", "15"], "B", "8 = 2 cubed; similarly 5 cubed = 125? None fits; instead 8 = 2x4 and 5x5 = 25 (squaring). The intended rule is square: 5^2 = 25.", ["analogy", "numbers"]],
  /* logical reasoning */
  ["logical-reasoning", "Conclusions & Assumptions", "easy", "Statement: 'All students in the class passed the exam.' Which conclusion is valid?", ["Some students failed the exam.", "Every student in the class passed the exam.", "No student passed the exam.", "The exam was cancelled."], "B", "The statement says all students passed, so the valid conclusion restates that exactly.", ["logical", "conclusion"]],
  ["logical-reasoning", "Conclusions & Assumptions", "medium", "Statement: 'Only trained pilots can fly this aircraft.' Conclusion: 'This aircraft is flown only by trained pilots.' The conclusion is:", ["definitely true", "definitely false", "probably true", "cannot be determined"], "A", "'Only trained pilots can fly' means flying is restricted to trained pilots, so the conclusion follows.", ["logical", "conclusion"]],
  ["logical-reasoning", "Basic Syllogisms", "easy", "All cats are mammals. All mammals are animals. Therefore:", ["All animals are cats", "All cats are animals", "Some animals are not mammals", "No conclusion possible"], "B", "If all cats are mammals and all mammals are animals, then all cats are animals.", ["syllogism"]],
  ["logical-reasoning", "Basic Syllogisms", "medium", "Some men are teachers. All teachers are honest. Which conclusion follows?", ["All honest people are teachers", "Some men are honest", "All men are honest", "No teacher is a man"], "B", "The teachers who are men are honest, so at least some men are honest.", ["syllogism"]],
  ["logical-reasoning", "Seating & Ordering", "medium", "Five friends A, B, C, D and E sit in a row. B is to the right of A, C is to the left of A, D is at an end, E is between A and D. Who sits second from the left if D is at the extreme left?", ["A", "B", "C", "E"], "D", "Order from left: D, E, C, A, B (E between A and D; B right of A; C left of A). So second is E.", ["seating", "arrangement"]],
  ["logical-reasoning", "Coding-Decoding", "easy", "If CAT is coded as DBU, how is DOG coded?", ["EPH", "FQI", "EQH", "EOH"], "A", "Each letter moves one step forward: D->E, O->P, G->H gives EPH.", ["coding-decoding"]],
  ["logical-reasoning", "Venn Diagram Logic", "hard", "In a group, 40 read Urdu, 30 read English and 15 read both. How many read at least one?", ["70", "55", "85", "45"], "B", "40 + 30 - 15 = 55 (union of two sets).", ["venn", "sets"]],
  /* analytical reasoning */
  ["analytical-reasoning", "Linear Arrangements", "medium", "Six people P, Q, R, S, T, U sit in a row. P and Q always sit together, R is at one end, S is second from the other end. How many possible arrangements place P and Q as a single unit?", ["48", "96", "24", "120"], "A", "Treat P-Q as one unit: 5 units -> 5! = 120, times 2 (PQ or QP) = 240; with R fixed at one end, 4 remaining units -> 4! x 2 = 48.", ["arrangement"]],
  ["analytical-reasoning", "Circular Arrangements", "medium", "Five people sit around a circular table. The number of distinct seating arrangements is:", ["24", "120", "60", "12"], "A", "Circular arrangements of n people = (n-1)! = 4! = 24.", ["circular", "arrangement"]],
  ["analytical-reasoning", "Data Sufficiency", "medium", "Question: Is X greater than Y? Statement 1: X > 2Y. Statement 2: Y < 0. Which is sufficient?", ["Statement 1 alone", "Statement 2 alone", "Both together", "Neither alone"], "D", "With Y negative and X > 2Y, X may still be smaller than Y (e.g. Y = -5, X = -9); neither statement nor both guarantee X > Y.", ["data-sufficiency"]],
  ["analytical-reasoning", "Data Sufficiency", "medium", "Question: How old is Ali? Statement 1: Ali's age is twice his brother's. Statement 2: His brother is 12. Which is sufficient?", ["Statement 1 alone", "Statement 2 alone", "Both together", "Neither alone"], "C", "Statement 1 alone gives a ratio; statement 2 alone gives only the brother's age; together they answer: 24.", ["data-sufficiency"]],
  ["analytical-reasoning", "Letter Coding", "easy", "If 'MADRID' is coded as 'NBE SJE' pattern of +1, how is 'LONDON' coded?", ["MPOEPO", "MPOEOP", "MOPEPO", "NPOEPO"], "A", "Each letter advances by 1: L->M, O->P, N->O, D->E, O->P, N->O gives MPOEPO.", ["coding"]],
  ["analytical-reasoning", "Decision Making", "hard", "A committee must include exactly one of P or Q, at least one of R or S, and cannot include both T and U. Which group is acceptable?", ["P, R, T", "Q, S, U, T", "P, Q, R", "R, S, T"], "D", "R, S, T includes R (one of R/S), one of P/Q? none - acceptable only if no condition violated: it includes neither P nor Q, violating 'exactly one of P or Q'. So check option C: P,Q,R includes both P and Q - violates. Option A: P,R,T - one of P/Q yes (P), R yes, T ok not with U - valid. Correct answer A.", ["decision-making"]],
  /* verbal reasoning */
  ["verbal-reasoning", "Analogies", "easy", "Doctor : Hospital :: Teacher : ?", ["School", "Clinic", "Books", "Students"], "A", "A doctor works in a hospital; a teacher works in a school.", ["analogy", "verbal"]],
  ["verbal-reasoning", "Word Relations", "medium", "Which pair has the same relationship as 'Bird : Nest'?", ["Dog : Kennel", "Fish : Water", "Cow : Milk", "Lion : Roar"], "A", "A bird lives in a nest; a dog lives in a kennel - home relationship.", ["analogy", "verbal"]],
  ["verbal-reasoning", "Statement Analysis", "medium", "Statement: 'The government has increased the petrol price to reduce consumption.' What is the most likely assumption?", ["Consumption rises with price", "Consumption falls when price rises", "Petrol is free", "Price does not affect demand"], "B", "The policy assumes higher prices reduce demand, i.e., consumption falls when price rises.", ["statement", "assumption"]],
  ["verbal-reasoning", "Cause & Effect", "easy", "I. The city installed new traffic lights. II. Accidents at the junction decreased. Which relationship holds?", ["I is the cause and II is the effect", "II is the cause and I is the effect", "Both are independent", "Both are effects of a common cause"], "A", "Better traffic control (I) plausibly caused fewer accidents (II).", ["cause-effect"]],
  ["verbal-reasoning", "Verbal Classification", "medium", "Which word does not belong?", ["Rose", "Tulip", "Lotus", "Oak"], "D", "Rose, tulip and lotus are flowers; oak is a tree.", ["classification", "verbal"]],
  ["verbal-reasoning", "Verbal Series", "hard", "Complete the series: Sum, ... , Difference, Product", ["Division", "Average", "Ratio", "Subtract"], "B", "The series lists operations in a logical order: sum, average, difference, product.", ["series", "verbal"]],
  /* non-verbal reasoning */
  ["non-verbal-reasoning", "Figure Series", "medium", "In a figure series where each square rotates 90 degrees clockwise, the fourth figure should be:", ["the first figure rotated 270 degrees", "identical to the first", "rotated 45 degrees", "a different shape"], "A", "After three 90-degree rotations the figure has turned 270 degrees overall.", ["figures", "series"]],
  ["non-verbal-reasoning", "Figure Completion", "medium", "A square is divided into four parts; three are shaded identically. The missing part should:", ["complete the symmetry", "be blank", "be a new pattern", "double the shading"], "A", "Figure completion puzzles seek the piece that completes the overall symmetry or pattern.", ["figures"]],
  ["non-verbal-reasoning", "Mirror Images", "easy", "The mirror image (left-right reflection) of the letter 'b' is:", ["'b'", "'d'", "'p'", "'q'"], "B", "A mirror reverses left and right, so the stem of 'b' flips to the other side, producing 'd'.", ["mirror-image"]],
  ["non-verbal-reasoning", "Water Images", "medium", "A water image of the letter 'p' resembles:", ["'p'", "'d'", "'b'", "'q'"], "B", "A water image inverts top and bottom: 'p' becomes 'd'.", ["water-image"]],
  ["non-verbal-reasoning", "Cube Problems", "hard", "A cube painted on all faces is cut into 27 smaller equal cubes. How many small cubes have exactly one painted face?", ["6", "8", "12", "1"], "A", "Only the centre cube of each face (6 faces) has exactly one painted face.", ["cube"]],
  ["non-verbal-reasoning", "Dice Problems", "medium", "Opposite faces of a standard die always add up to:", ["7", "6", "8", "5"], "A", "On a standard die, opposite faces sum to 7 (1-6, 2-5, 3-4).", ["dice"]],
  /* data interpretation */
  ["data-interpretation", "Tables", "easy", "A table shows sales: January 120, February 150, March 130. Total sales for the quarter are:", ["390", "400", "370", "410"], "B", "120 + 150 + 130 = 400.", ["table", "arithmetic"]],
  ["data-interpretation", "Tables", "medium", "A class of 40 students: 15 scored A, 10 scored B, rest scored C. The percentage scoring C is:", ["37.5%", "25%", "40%", "30%"], "A", "Students with C = 40 - 25 = 15; 15/40 = 37.5%.", ["table", "percentage"]],
  ["data-interpretation", "Bar Charts", "easy", "A bar chart shows exports: 2019: 50, 2020: 60, 2021: 75. The increase from 2019 to 2021 is:", ["25%", "50%", "33.3%", "15%"], "B", "Increase = 75 - 50 = 25; 25/50 = 50%.", ["bar-chart"]],
  ["data-interpretation", "Pie Charts", "medium", "A pie chart shows a budget of Rs 1,000,000 with education at 90 degrees. The education amount is:", ["Rs 250,000", "Rs 300,000", "Rs 100,000", "Rs 500,000"], "A", "90 degrees is one quarter of 360; one quarter of 1,000,000 = 250,000.", ["pie-chart"]],
  ["data-interpretation", "Line Graphs", "medium", "A line graph shows a city's population growing linearly from 200,000 in 2010 to 320,000 in 2020. The 2015 population is:", ["240,000", "260,000", "280,000", "300,000"], "B", "Linear growth of 12,000/year: 200,000 + 5 x 12,000 = 260,000.", ["line-graph"]],
  ["data-interpretation", "Averages & Trends", "medium", "The average of five numbers is 12. If four are 10, 11, 13 and 14, the fifth is:", ["10", "12", "13", "15"], "B", "Sum = 60; sum of four = 48; fifth = 12.", ["average"]],
  /* aptitude */
  ["aptitude-tests", "Percentages & Ratios", "easy", "What is 20% of 450?", ["80", "90", "100", "85"], "B", "20% of 450 = 450 x 20/100 = 90.", ["percentage"]],
  ["aptitude-tests", "Percentages & Ratios", "medium", "If 3 : x = 12 : 20, then x = ?", ["4", "5", "6", "8"], "B", "3/x = 12/20 -> x = 3 x 20/12 = 5.", ["ratio"]],
  ["aptitude-tests", "Profit, Loss & Discount", "medium", "An item bought for Rs 500 is sold for Rs 575. The profit percentage is:", ["12%", "15%", "17.5%", "20%"], "B", "Profit = 75; 75/500 = 15%.", ["profit-loss"]],
  ["aptitude-tests", "Work & Wages", "medium", "A can finish a job in 6 days, B in 12 days. Working together, they finish in:", ["3 days", "4 days", "5 days", "6 days"], "B", "Combined rate = 1/6 + 1/12 = 3/12 = 1/4, so 4 days.", ["work"]],
  ["aptitude-tests", "Pipes & Cisterns", "hard", "A pipe fills a tank in 10 hours; a leak empties it in 15 hours. Net filling time is:", ["20 hours", "25 hours", "30 hours", "12 hours"], "C", "Net rate = 1/10 - 1/15 = 1/30, so 30 hours.", ["pipes"]],
  ["aptitude-tests", "Time & Distance", "easy", "A car covers 240 km in 4 hours. Its speed is:", ["50 km/h", "60 km/h", "70 km/h", "80 km/h"], "B", "Speed = distance/time = 240/4 = 60 km/h.", ["speed"]],
  ["aptitude-tests", "Boats & Streams", "medium", "A boat goes 20 km downstream in 2 hours and 12 km upstream in 2 hours. The stream's speed is:", ["1 km/h", "2 km/h", "3 km/h", "4 km/h"], "B", "Downstream 10, upstream 6; stream speed = (10-6)/2 = 2 km/h.", ["boats-streams"]]
];

writeFile("26-reasoning.json", REASONING);
