const { writeFile } = require("./gen-helper.cjs");

const WCA = [
  ["world-current-affairs", "UN System & Agencies", "easy", "The United Nations was founded in the year:", ["1945", "1919", "1950", "1939"], "A", "The UN Charter was signed in San Francisco on 26 June 1945 and entered force that October.", ["current-affairs", "un"]],
  ["world-current-affairs", "UN System & Agencies", "easy", "The headquarters of the United Nations is located in:", ["New York", "Geneva", "Paris", "London"], "A", "UN headquarters is in New York; Geneva hosts European offices.", ["current-affairs", "un"]],
  ["world-current-affairs", "UN System & Agencies", "medium", "Which UN agency focuses on children's welfare?", ["UNICEF", "WHO", "ILO", "FAO"], "A", "UNICEF (United Nations Children's Fund) protects children worldwide.", ["current-affairs", "un"]],
  ["world-current-affairs", "UN System & Agencies", "medium", "The International Court of Justice sits in:", ["The Hague", "New York", "Vienna", "Rome"], "A", "The ICJ, the UN's principal judicial organ, is based in The Hague.", ["current-affairs", "un"]],
  ["world-current-affairs", "IMF, WTO, BRICS & Bodies", "easy", "The World Trade Organization (WTO) primarily deals with:", ["rules of trade between nations", "military alliances", "space exploration", "climate only"], "A", "The WTO administers global trade agreements and settles trade disputes.", ["current-affairs", "wto"]],
  ["world-current-affairs", "IMF, WTO, BRICS & Bodies", "medium", "BRICS is a group of major emerging economies; Pakistan is:", ["not a member", "a founding member", "the chair", "an observer only"], "A", "BRICS comprises Brazil, Russia, India, China, South Africa and newer members; Pakistan is not a member.", ["current-affairs", "brics"]],
  ["world-current-affairs", "Trade Blocs & Agreements", "medium", "CPEC is a corridor linking Pakistan with:", ["China", "India", "Iran", "Turkey"], "A", "The China-Pakistan Economic Corridor connects Gwadar to China's western region.", ["current-affairs", "cpec"]],
  ["world-current-affairs", "Global Economic Trends", "medium", "SDRs are an international reserve asset issued by the:", ["IMF", "World Bank", "ADB", "WTO"], "A", "Special Drawing Rights are IMF reserve assets supplementing member reserves.", ["current-affairs", "imf"]],
  ["world-current-affairs", "Recent Conflicts", "medium", "The 'Red Sea crisis' affecting global shipping since late 2023 is linked to attacks by:", ["Houthi forces in Yemen", "pirates in the Caribbean", "submarines in the Arctic", "smugglers in the Aegean"], "A", "Houthi attacks on shipping in the Red Sea disrupted the Suez route, raising freight costs.", ["current-affairs"]],
  ["world-current-affairs", "Peace & Diplomacy", "hard", "The Treaty on the Prohibition of Nuclear Weapons (TPNW), which entered into force in 2021, bans:", ["nuclear weapons outright", "conventional bombs", "drones", "chemical sprays"], "A", "TPNW prohibits developing, testing and possessing nuclear weapons; nuclear states have not joined.", ["current-affairs", "nuclear"]],
  ["world-current-affairs", "UN System & Agencies", "medium", "Pakistan's permanent representative to the UN presents the country's position at the:", ["General Assembly", "Security Council only", "World Bank", "ICJ only"], "A", "Pakistan addresses the UN General Assembly annually; it has also served on the Security Council.", ["current-affairs", "un"]],
  ["world-current-affairs", "Global Economic Trends", "medium", "The Shanghai Cooperation Organization (SCO) is primarily a:", ["political and security grouping", "trade union", "sports federation", "health agency"], "A", "The SCO, which includes China, Russia and Pakistan, focuses on regional security and cooperation.", ["current-affairs", "sco"]]
];

writeFile("34-world-current.json", WCA);
