const { writeFile } = require("./gen-helper.cjs");

const LANGUAGE = [
  /* vocabulary */
  ["vocabulary", "Common Exam Words", "easy", "The word 'meticulous' most nearly means:", ["careless", "extremely careful", "quick", "stubborn"], "B", "Meticulous means showing great attention to detail and being extremely careful in work.", ["vocabulary", "synonym", "css"]],
  ["vocabulary", "Common Exam Words", "easy", "Choose the closest synonym of 'benevolent':", ["harsh", "kind-hearted", "greedy", "timid"], "B", "Benevolent means well-meaning and kind; a benevolent person gives help generously.", ["vocabulary", "synonym"]],
  ["vocabulary", "Common Exam Words", "medium", "The antonym of 'ephemeral' is:", ["permanent", "brief", "fragile", "sudden"], "A", "Ephemeral means lasting for a very short time; its opposite is permanent or enduring.", ["vocabulary", "antonym"]],
  ["vocabulary", "Common Exam Words", "medium", "'Ubiquitous' means:", ["rare", "present everywhere", "unclear", "unlawful"], "B", "Ubiquitous describes something found everywhere, such as mobile phones in modern life.", ["vocabulary", "synonym"]],
  ["vocabulary", "Roots, Prefixes & Suffixes", "easy", "The prefix 'anti-' as in 'antibiotic' means:", ["with", "against", "before", "between"], "B", "The Greek prefix anti- means against; an antibiotic acts against bacteria.", ["vocabulary", "prefix"]],
  ["vocabulary", "Roots, Prefixes & Suffixes", "medium", "What does the root 'biblio' mean?", ["book", "light", "earth", "water"], "A", "Biblio comes from Greek biblion (book); it appears in words like bibliography.", ["vocabulary", "roots"]],
  ["vocabulary", "Confusable Pairs", "easy", "Choose the correct word: 'The principal gave a (complement / compliment) to the students'.", ["complement", "compliment", "complimently", "complementing"], "B", "Compliment means praise; complement means to complete or go well with something.", ["vocabulary", "confusable"]],
  ["vocabulary", "Confusable Pairs", "medium", "Select the correct word: 'The car's brakes began to (falter / flounder) on the steep slope'.", ["falter", "flounder", "flounder and falter are identical", "neither fits"], "A", "Falter means to lose strength or hesitate; flounder means to struggle clumsily in difficulty.", ["vocabulary", "confusable"]],
  /* grammar */
  ["grammar", "Nouns & Pronouns", "easy", "Choose the correct sentence:", ["Each of the boys have a book.", "Each of the boys has a book.", "Each of the boys are having books.", "Each of the boys were given books."], "B", "Each is singular, so the verb must be singular: 'has' agrees with the singular subject.", ["grammar", "agreement"]],
  ["grammar", "Verbs & Tenses", "easy", "She has been working here since 2015. This sentence is in the:", ["past perfect tense", "present perfect continuous tense", "past continuous tense", "simple present tense"], "B", "Has/have been + -ing shows the present perfect continuous tense, describing an action continuing from the past.", ["grammar", "tense"]],
  ["grammar", "Subject-Verb Agreement", "medium", "Identify the error: 'The team of players were arriving early'.", ["The", "of", "were", "arriving"], "C", "The subject 'team' is singular, so the verb should be 'was arriving', not 'were'.", ["grammar", "agreement"]],
  ["grammar", "Clauses & Phrases", "medium", "In 'The man who called you has left', the clause 'who called you' is a:", ["noun clause", "relative clause", "adverbial clause", "conditional clause"], "B", "A relative clause begins with a relative pronoun (who) and modifies the noun 'man'.", ["grammar", "clause"]],
  ["grammar", "Common Errors", "easy", "Choose the correct form: 'Neither the manager nor the employees ___ satisfied'.", ["is", "are", "was", "has been"], "B", "With 'neither...nor', the verb agrees with the nearer subject; 'employees' is plural so 'are' is correct.", ["grammar", "agreement"]],
  ["grammar", "Punctuation", "medium", "Which sentence is punctuated correctly?", ["What is your name, she asked.", "What is your name? she asked.", "'What is your name?' she asked.", "What is your name! she asked."], "C", "Direct speech is enclosed in quotation marks, and the question is followed by a question mark.", ["grammar", "punctuation"]],
  ["grammar", "Verbs & Tenses", "medium", "By this time next year, he ___ his degree.", ["will complete", "will have completed", "completes", "completed"], "B", "'By this time next year' points to a future point, so the future perfect tense fits: will have completed.", ["grammar", "tense"]],
  /* synonyms */
  ["synonyms", "High-Frequency Synonyms", "easy", "Choose the synonym of 'abundant':", ["scarce", "plentiful", "empty", "weak"], "B", "Abundant means existing in large quantities; plentiful is its closest match.", ["synonym"]],
  ["synonyms", "High-Frequency Synonyms", "easy", "A synonym of 'reluctant' is:", ["eager", "unwilling", "angry", "confused"], "B", "Reluctant means hesitant or unwilling to do something.", ["synonym"]],
  ["synonyms", "High-Frequency Synonyms", "medium", "The word closest in meaning to 'obsolete' is:", ["modern", "outdated", "useful", "visible"], "B", "Obsolete means no longer in use; outdated matches it closely.", ["synonym"]],
  ["synonyms", "Context-Based Synonyms", "medium", "In 'the verdict was unanimous', 'unanimous' means:", ["divided", "agreed by all", "delayed", "unknown"], "B", "Unanimous means fully in agreement; every member of the jury agreed.", ["synonym"]],
  ["synonyms", "Context-Based Synonyms", "medium", "Choose the synonym of 'intricate':", ["simple", "complex", "costly", "lengthy"], "B", "Intricate means very complicated or detailed, i.e., complex.", ["synonym"]],
  ["synonyms", "Word Families", "hard", "Which word is a synonym of 'loquacious'?", ["silent", "talkative", "lazy", "generous"], "B", "Loquacious means very talkative, derived from Latin loqui, to speak.", ["synonym"]],
  /* antonyms */
  ["antonyms", "High-Frequency Antonyms", "easy", "Choose the antonym of 'diligent':", ["hardworking", "lazy", "careful", "honest"], "B", "Diligent means industrious and hardworking; lazy is its opposite.", ["antonym"]],
  ["antonyms", "High-Frequency Antonyms", "easy", "The antonym of 'transparent' is:", ["clear", "opaque", "thin", "bright"], "B", "Transparent means allowing light through; opaque means not allowing light to pass.", ["antonym"]],
  ["antonyms", "High-Frequency Antonyms", "medium", "Choose the antonym of 'vague':", ["clear", "fuzzy", "dim", "doubtful"], "A", "Vague means unclear or imprecise; clear is its direct opposite.", ["antonym"]],
  ["antonyms", "Prefix-Based Opposites", "medium", "Which prefix forms the antonym of 'logical'?", ["in-", "dis-", "mis-", "pre-"], "A", "Illogical is formed with the negative prefix 'il-' (variant of in-), giving the opposite of logical.", ["antonym", "prefix"]],
  ["antonyms", "Prefix-Based Opposites", "medium", "The opposite of 'credible' is:", ["incredible", "creditable", "accredited", "reliable"], "A", "Credible means believable; incredible (in- + credible) means not believable.", ["antonym", "prefix"]],
  ["antonyms", "Shades of Meaning", "hard", "Choose the best antonym of 'lament' in context: 'The nation continued to lament its losses'.", ["celebrate", "mourn", "accept", "discuss"], "A", "To lament is to mourn or express grief; to celebrate is the opposite feeling.", ["antonym"]],
  /* idioms */
  ["idioms", "Everyday Idioms", "easy", "The idiom 'to bite the bullet' means:", ["to eat quickly", "to face a painful situation bravely", "to stop working", "to get angry"], "B", "Biting the bullet means enduring something difficult or painful with courage.", ["idiom"]],
  ["idioms", "Everyday Idioms", "easy", "'A blessing in disguise' means:", ["something bad that brings good results", "a hidden treasure", "an obvious gift", "a short visit"], "A", "A blessing in disguise is an apparent misfortune that turns out to be beneficial.", ["idiom"]],
  ["idioms", "Body-Part Idioms", "medium", "The idiom 'to pull someone's leg' means:", ["to trip someone", "to tease or joke with someone", "to help someone", "to ignore someone"], "B", "To pull someone's leg is to tease them playfully, usually with a harmless joke.", ["idiom"]],
  ["idioms", "Body-Part Idioms", "medium", "'To cost an arm and a leg' means:", ["to be very expensive", "to be painful", "to be risky", "to be cheap"], "A", "The idiom means something is extremely expensive, as if you paid with a body part.", ["idiom"]],
  ["idioms", "Phrasal Verbs", "medium", "The phrasal verb 'to put off' means:", ["to postpone", "to start", "to praise", "to remove clothes"], "A", "To put off means to delay or postpone something to a later time.", ["idiom", "phrasal verb"]],
  ["idioms", "Idioms in Context", "hard", "In 'After years of struggle, the project finally came to fruition', 'came to fruition' means:", ["was abandoned", "became successful", "became expensive", "was delayed"], "B", "To come to fruition means to achieve successful results after effort and time.", ["idiom"]],
  /* sentence correction */
  ["sentence-correction", "Agreement Errors", "easy", "Select the correct option:", ["The number of applicants are increasing.", "The number of applicants is increasing.", "A number of applicant is increasing.", "The numbers of applicants is increasing."], "B", "'The number of' takes a singular verb because the subject is 'number'.", ["sentence-correction", "agreement"]],
  ["sentence-correction", "Agreement Errors", "medium", "Correct the error: 'Either of the two answers are correct'.", ["Either", "of", "are", "correct"], "C", "'Either' is singular, so the verb must be 'is' not 'are'.", ["sentence-correction", "agreement"]],
  ["sentence-correction", "Tense & Mood Errors", "medium", "Identify the error: 'When I reached the station, the train already left'.", ["When", "reached", "already", "left"], "D", "The past perfect is needed: 'the train had already left' before I reached the station.", ["sentence-correction", "tense"]],
  ["sentence-correction", "Tense & Mood Errors", "medium", "Pick the correct sentence:", ["I wish I was taller.", "I wish I were taller.", "I wish I am taller.", "I wish I be taller."], "B", "For wishes, the subjunctive form 'were' is used regardless of the subject.", ["sentence-correction", "subjunctive"]],
  ["sentence-correction", "Sentence Improvement", "medium", "Select the best version: 'He is one of the boys who has passed the test'.", ["He is one of the boys who has passed the test.", "He is one of the boys who have passed the test.", "He is one of the boy who have passed the test.", "He is one of boys who passed the test."], "B", "The relative clause refers to 'boys' (plural), so 'have passed' agrees with the antecedent.", ["sentence-correction"]],
  ["sentence-correction", "Sentence Reconstruction", "hard", "Choose the most concise correct sentence:", ["The reason why he failed was because he did not study.", "The reason he failed was because of not studying.", "He failed because he did not study.", "The reason for his failure was due to the fact he did not study."], "C", "Option C is the clearest and most concise; the others are wordy or redundant.", ["sentence-correction"]],
  /* comprehension */
  ["comprehension", "Main Idea & Tone", "easy", "Read: 'Solar power converts sunlight directly into electricity. It is clean, silent and increasingly affordable. For remote villages that lack a power grid, solar panels can transform daily life.' The main idea is:", ["solar power is expensive", "solar power can improve life where electricity is unavailable", "villages dislike solar power", "solar panels are noisy"], "B", "The passage stresses solar power's benefits, especially for remote areas without a grid.", ["comprehension"]],
  ["comprehension", "Main Idea & Tone", "medium", "Read: 'The committee's proposal was thorough, but its cost estimates were optimistic and its timetable unrealistic.' The author's tone is:", ["approving", "critical but measured", "angry", "indifferent"], "B", "The author acknowledges strengths (thorough) but points out weaknesses in measured, restrained language.", ["comprehension", "tone"]],
  ["comprehension", "Inference & Detail", "medium", "Read: 'Although the glacier has retreated two kilometres since 1980, it still feeds the river that waters the valley.' What can be inferred?", ["the glacier has stopped moving", "the river depends partly on the glacier", "the valley has no other water source", "glaciers never retreat"], "B", "The word 'still' shows the glacier continues to supply the river even after retreating.", ["comprehension", "inference"]],
  ["comprehension", "Cloze Tests", "medium", "Choose the correct word: 'The scientist remained calm and ___ even when the experiment failed'.", ["methodical", "methodically", "method", "methodologist"], "A", "An adjective is needed after 'calm and'; methodical describes a careful, systematic person.", ["comprehension", "cloze"]]
];

writeFile("25-language-ability.json", LANGUAGE);
