const { writeFile } = require("./gen-helper.cjs");

const IT = [
  /* machine learning */
  ["machine-learning", "Supervised Learning", "easy", "In supervised learning, the training data includes:", ["input features only", "input features and labels", "labels only", "unlabeled clusters"], "B", "Supervised learning trains on input-output pairs, i.e., features with known labels.", ["ml", "supervised"]],
  ["machine-learning", "Supervised Learning", "easy", "Which task is an example of classification?", ["predicting house prices", "grouping customers by similarity", "detecting spam emails", "reducing data dimensions"], "C", "Spam detection assigns discrete categories (spam / not spam), which is classification.", ["ml", "classification"]],
  ["machine-learning", "Regression & Classification", "medium", "Linear regression predicts:", ["categorical labels", "continuous numeric values", "clusters", "rules"], "B", "Regression models predict a continuous numeric output, e.g. price or temperature.", ["ml", "regression"]],
  ["machine-learning", "Clustering", "medium", "K-means is an example of:", ["supervised learning", "unsupervised learning", "reinforcement learning", "semi-supervised learning"], "B", "K-means groups unlabeled data into clusters, so it is unsupervised.", ["ml", "clustering"]],
  ["machine-learning", "Overfitting & Regularization", "hard", "A model performs perfectly on training data but poorly on new data. This is called:", ["underfitting", "overfitting", "bias", "noise"], "B", "Overfitting means the model memorized training data and fails to generalize to unseen data.", ["ml", "overfitting"]],
  ["machine-learning", "Metrics", "medium", "Accuracy alone can mislead when:", ["classes are balanced", "classes are imbalanced", "data is numeric", "data is small"], "B", "With imbalanced classes, accuracy can be high while the minority class is ignored; precision/recall help.", ["ml", "metrics"]],
  /* deep learning */
  ["deep-learning", "Perceptron & Layers", "easy", "A neural network's first layer is called the:", ["output layer", "input layer", "hidden layer", "dropout layer"], "B", "The input layer receives the raw features; hidden layers sit between input and output.", ["dl", "neural-network"]],
  ["deep-learning", "Activation Functions", "easy", "Which activation function maps values to a range between 0 and 1?", ["ReLU", "Sigmoid", "Tanh", "Linear"], "B", "The sigmoid function squashes outputs into (0, 1), useful for probabilities.", ["dl", "activation"]],
  ["deep-learning", "Convolutional Networks", "medium", "Convolutional neural networks are most commonly used for:", ["time series only", "image data", "text embeddings only", "database queries"], "B", "CNNs excel at image processing by learning spatial features through filters.", ["dl", "cnn"]],
  ["deep-learning", "Transformer Architecture", "medium", "The 'attention' mechanism in transformers allows the model to:", ["ignore context", "weigh the importance of different words in a sequence", "compress images", "sort data"], "B", "Attention scores how relevant each token is to others, capturing context across the sequence.", ["dl", "transformer", "llm"]],
  ["deep-learning", "Attention & Embeddings", "hard", "Word embeddings represent words as:", ["single numbers", "dense vectors of numbers", "characters", "binary trees"], "B", "Embeddings map words to dense numeric vectors so similar words have similar vectors.", ["dl", "embedding"]],
  /* ethical hacking */
  ["ethical-hacking", "Threats & Vulnerabilities", "easy", "A 'phishing' attack primarily targets:", ["hardware", "human users", "routers", "databases"], "B", "Phishing deceives users into revealing credentials or installing malware.", ["security", "phishing"]],
  ["ethical-hacking", "Threats & Vulnerabilities", "easy", "Malware that locks files and demands payment is called:", ["adware", "ransomware", "spyware", "worm"], "B", "Ransomware encrypts files and demands a ransom for decryption.", ["security", "malware"]],
  ["ethical-hacking", "Reconnaissance", "medium", "In penetration testing, 'reconnaissance' is the phase of:", ["exploiting vulnerabilities", "gathering information about the target", "cleaning logs", "writing reports"], "B", "Reconnaissance (passive or active) collects target information before any exploitation.", ["pentest", "recon"]],
  ["ethical-hacking", "Hardening", "medium", "Which practice best hardens a web server?", ["disabling unnecessary services", "removing the firewall", "using default passwords", "opening all ports"], "A", "Disabling unneeded services reduces the attack surface of a server.", ["security", "hardening"]],
  ["ethical-hacking", "Exploitation & Post-Exploitation", "hard", "After gaining access in a test, 'privilege escalation' means:", ["losing access", "obtaining higher-level access rights", "deleting the target", "scanning ports again"], "B", "Privilege escalation moves from a limited account to a higher-privileged one.", ["pentest"]],
  ["ethical-hacking", "Incident Response", "medium", "The first step in incident response is usually:", ["recovery", "preparation and detection", "lawsuits", "public announcement"], "B", "Preparation and detection identify the incident before containment and recovery.", ["security", "incident-response"]],
  /* devops */
  ["devops", "Pipeline Fundamentals", "easy", "In CI/CD, 'CI' stands for:", ["Continuous Integration", "Central Installation", "Code Inspection", "Continuous Interface"], "A", "Continuous Integration merges code changes frequently and runs automated tests.", ["devops", "cicd"]],
  ["devops", "Pipeline Fundamentals", "easy", "A 'build' step in a pipeline typically:", ["compiles code and runs tests", "deletes the repository", "sends emails", "buys servers"], "A", "The build stage compiles the application and usually runs automated tests.", ["devops", "cicd"]],
  ["devops", "Terraform & Ansible", "medium", "Terraform is primarily used for:", ["containerizing apps", "infrastructure as code provisioning", "writing unit tests", "monitoring logs"], "B", "Terraform declaratively provisions cloud infrastructure as code.", ["devops", "iac", "terraform"]],
  ["devops", "Configuration Management", "medium", "Which tool is known for configuration management and playbooks?", ["Ansible", "GitHub", "Photoshop", "Postman"], "A", "Ansible manages configuration with YAML playbooks over SSH.", ["devops", "ansible"]],
  ["devops", "Observability", "medium", "Which three pillars are commonly associated with observability?", ["logs, metrics, traces", "code, tests, builds", "CPU, RAM, disk", "DNS, HTTP, TCP"], "A", "Logs, metrics and traces together give observability into system behaviour.", ["devops", "monitoring"]],
  ["devops", "Build & Release", "hard", "A 'blue-green deployment' involves:", ["two identical environments with instant switchover", "deleting the old version", "rolling back to source code", "renaming the server"], "A", "Blue-green deploys to an idle environment then switches traffic, enabling instant rollback.", ["devops", "deployment"]],
  /* big data */
  ["big-data", "The 3 V's", "easy", "The three V's of big data are:", ["volume, velocity, variety", "value, virus, vector", "version, vendor, value", "velocity, vision, volume"], "A", "Big data is characterized by large Volume, high Velocity and wide Variety of data.", ["bigdata"]],
  ["big-data", "Hadoop Ecosystem", "easy", "HDFS stands for:", ["Hadoop Distributed File System", "High Data File System", "Hadoop Data Frame Store", "Hyper Distributed Framework"], "A", "HDFS is Hadoop's distributed, fault-tolerant file storage layer.", ["bigdata", "hadoop"]],
  ["big-data", "MapReduce", "medium", "In MapReduce, the 'Reduce' phase typically:", ["sorts input data", "aggregates or summarizes mapped data", "stores raw files", "renders charts"], "B", "After Map produces key-value pairs, Reduce aggregates them into final results.", ["bigdata", "mapreduce"]],
  ["big-data", "Spark", "medium", "Apache Spark differs from classic MapReduce by:", ["using in-memory processing", "running only on one machine", "not supporting SQL", "being a database"], "A", "Spark's in-memory engine makes iterative and interactive jobs far faster.", ["bigdata", "spark"]],
  ["big-data", "Streaming", "medium", "Kafka is best described as a:", ["distributed event streaming platform", "relational database", "web server", "static file host"], "A", "Kafka streams events between producers and consumers at high throughput.", ["bigdata", "kafka"]],
  /* database */
  ["database", "Tables & Keys", "easy", "A primary key must be:", ["unique and non-null", "always a number", "optional", "duplicated across rows"], "A", "A primary key uniquely identifies each row and cannot be null.", ["database", "keys"]],
  ["database", "Normalization", "easy", "Removing duplicate data and splitting tables reduces:", ["redundancy", "security", "speed always", "queries"], "A", "Normalization eliminates redundancy, improving consistency.", ["database", "normalization"]],
  ["database", "Normalization", "medium", "A table in 3NF must already be in:", ["1NF and 2NF", "no normal form", "only 1NF", "BCNF"], "A", "Normal forms build on each other: 3NF requires 2NF which requires 1NF.", ["database", "normalization"]],
  ["database", "ER Modeling", "medium", "In an ER diagram, a 'relationship' is drawn as a:", ["rectangle", "diamond", "ellipse", "circle"], "B", "Entities are rectangles, attributes ellipses, and relationships diamonds.", ["database", "er"]],
  ["database", "Transactions & ACID", "medium", "The 'A' in ACID stands for:", ["Atomicity", "Accuracy", "Access", "Availability"], "A", "Atomicity ensures a transaction fully completes or fully rolls back.", ["database", "acid"]],
  ["database", "Indexes & Constraints", "medium", "Adding an index to a column typically:", ["speeds up searches on that column", "always slows all queries", "deletes the column", "removes constraints"], "A", "Indexes accelerate lookups and filtering at the cost of write overhead.", ["database", "index"]],
  /* sql */
  ["sql", "SELECT & Filtering", "easy", "Which clause filters rows in SQL?", ["WHERE", "ORDER BY", "GROUP BY", "SELECT"], "A", "WHERE applies row-level conditions before grouping or ordering.", ["sql", "select"]],
  ["sql", "SELECT & Filtering", "easy", "To fetch all columns of table 'students', you write:", ["SELECT * FROM students;", "SELECT all FROM students;", "FETCH * FROM students;", "GET * students;"], "A", "SELECT * retrieves every column from the table.", ["sql"]],
  ["sql", "Joins", "medium", "An INNER JOIN returns rows that have:", ["matching values in both tables", "only unmatched left rows", "only unmatched right rows", "all rows regardless of match"], "A", "INNER JOIN keeps only rows with matches in both joined tables.", ["sql", "join"]],
  ["sql", "Aggregations & Grouping", "medium", "Which function returns the number of rows in a group?", ["COUNT()", "SUM()", "AVG()", "LEN()"], "A", "COUNT() counts rows or non-null values in a group.", ["sql", "aggregation"]],
  ["sql", "Aggregations & Grouping", "medium", "The HAVING clause filters:", ["groups after aggregation", "rows before grouping", "columns in output", "table names"], "A", "HAVING applies conditions to grouped results, unlike WHERE which filters rows.", ["sql"]],
  ["sql", "Subqueries", "hard", "A subquery that returns a single value is called a:", ["scalar subquery", "vector query", "compound query", "nested table"], "A", "A scalar subquery returns one row and one column and can be used in comparisons.", ["sql", "subquery"]],
  /* windows */
  ["windows", "Desktop & Files", "easy", "In Windows, which shortcut copies a file?", ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], "A", "Ctrl+C copies; Ctrl+V pastes; Ctrl+X cuts; Ctrl+Z undoes.", ["windows"]],
  ["windows", "Desktop & Files", "easy", "The Windows tool that manages disk space is called:", ["Disk Management", "Paint", "Notepad", "Calculator"], "A", "Disk Management (diskmgmt.msc) handles partitions and volumes.", ["windows"]],
  ["windows", "Settings & Control Panel", "medium", "Which command opens the System Configuration utility?", ["msconfig", "cmd", "regedit", "taskmgr"], "A", "msconfig launches System Configuration; taskmgr opens Task Manager.", ["windows"]],
  ["windows", "Networking & Sharing", "medium", "The Windows firewall can be configured from:", ["Windows Defender Firewall", "Disk Management", "Device Manager", "Event Viewer"], "A", "Windows Defender Firewall controls inbound and outbound rules.", ["windows", "network"]],
  /* linux */
  ["linux", "Command Line Basics", "easy", "Which command lists files in Linux?", ["ls", "dir only", "list", "show"], "A", "'ls' is the standard command to list directory contents.", ["linux"]],
  ["linux", "Command Line Basics", "easy", "To change directories in the terminal, use:", ["cd", "chdir old", "mv", "go"], "A", "'cd' (change directory) navigates the file system.", ["linux"]],
  ["linux", "File System", "medium", "In Linux, everything is treated as:", ["a file", "a process", "a window", "a service"], "A", "The Unix philosophy treats devices, sockets and files uniformly as files.", ["linux"]],
  ["linux", "Processes & Permissions", "medium", "The command 'chmod 755' gives the owner:", ["read, write, execute", "read only", "no access", "write only"], "A", "7 = rwx for the owner; 5 = r-x for group and others.", ["linux", "permissions"]],
  ["linux", "Package Management", "medium", "On Debian-based systems, package installation uses:", ["apt", "yum only", "brew", "pip only"], "A", "APT is the package manager on Debian/Ubuntu; yum is Red Hat.", ["linux", "packages"]],
  ["linux", "Scripting Basics", "hard", "A shell script's first line '#!/bin/bash' is called:", ["the shebang", "the header", "the comment", "the alias"], "A", "The shebang tells the kernel which interpreter to execute the script with.", ["linux", "shell"]]
];

writeFile("27-it.json", IT);
